config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    passwords: 'public/users/passwords',
    registrations: 'public/users/registrations',
  }
  scope module: :public do
    root 'homes#top'
    resources :events, only: [:show, :index]
    resources :users, only: [:show, :edit, :index, :update] do
      resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
    end
    resources :rooms, only: [:show, :index]
    resources :direct_messages, only: [:create]
    resources :notifications, only: [:index, :destroy]
  end

  namespace :admin do
    resources :users, only: [:show] do
      resources :todos, only: [:create, :destroy]
    end
    resources :events, only: [:show, :index, :edit, :create, :update, :destroy]
    get 'step1', to: 'events#step1'
    post 'step2', to: 'events#step2'
    get 'step3', to: 'events#step3'
    post 'step4', to: 'events#step4'
    post 'confirm', to: 'events#confirm'

    get 'events/:event_id/send_remind', to: 'events#send_remind', as: 'events_send_remind'
    patch 'events/:event_id/progress_status_update', to: 'events#progress_status_update', as: 'events_progress_status'
    get 'events/:event_id/notice_to_unpaying_users', to: 'events#notice_to_unpaying_users', as: 'notice_to_unpaying_users'
    get 'events/:event_id/add_event_user', to: 'events#add_event_user', as: 'add_event_user'
    post 'events/:event_id/add_event_user_fee', to: 'events#add_event_user_fee', as: 'add_event_user_fee'
    post 'events/:event_id/add_event_user', to: 'events#add_event_user_create', as: 'add_event_user_create'
    get 'events/:event_id/change_restaurant', to: 'events#change_restaurant', as: 'change_restaurant'
    patch 'event_users/:event_user_id/fee_status', to: 'event_users#fee_status_update', as: 'event_users_fee_status'
    patch 'event_users/:event_user_id/fee', to: 'event_users#fee_update', as: 'event_users_fee'
    patch 'event_users/:event_user_id/participate_status', to: 'event_users#participate_status_update', as: 'event_users_participate_status'

    resources :rooms, only: [:show, :index]
    resources :direct_messages, only: [:create]
    resources :notifications, only: [:index, :destroy]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  # ==============バリデーション ================================
  # user_id,restaurant_idはコントローラーで代入、progress_status,fee_statusはデフォルトで設定あり
  with_options presence: true do
    validates :name
    validates :date
    validates :begin_time
    validates :finish_time
  end

  # ==============アソシエーション ================================
  # ◆飲食店
  belongs_to :restaurant, optional: true
  # ◆ノミカイユーザー（中間テーブル）
  has_many :event_users, dependent: :destroy
  # ◆通知
  has_many :notifications, dependent: :destroy

  # ==================メソッド=====================================
  # ◆カレンダー：gem simple_calendarでは"start_time"と"end_time"ベースでカレンダーのdayに入る。今回は日付と時間の入力を分けており、時間カラムには今日に日付が入ってしまうため、simple_calendarの仕様踏まえて明示的にstart_timeとend_timeを日付カラムの日にちに設定しなければならない。そのため開始時間と終了時間の命名をかぶらないようにbegin_timeとfinish_timeにした。
  def start_time
    date
  end

  def end_time
    date
  end

  # ◆通知機能（未払いのメンバーへの支払い依頼）
  def create_notification_require_fee(current_user, visited_id)
    notification = current_user.active_notifications.new(
      event_id: id,
      visited_id: visited_id,
      action: 'require_fee'
    )
    notification.save if notification.valid?
  end

  # ◆通知機能（新規ノミカイ案内）
  def create_notification_new_event(current_user, visited_id)
    notification = current_user.active_notifications.new(
      event_id: id,
      visited_id: visited_id,
      action: 'create_event'
    )
    # 自分へは通知が作られない・届かないようにする
    notification.save if notification.visitor_id != notification.visited_id && notification.valid?
  end

  # ◆通知機能（リマインド）
  def create_notification_remind_event(current_user, visited_id)
    notification = current_user.active_notifications.new(
      event_id: id,
      visited_id: visited_id,
      action: 'remind_event'
    )
    # 自分へは通知が作られない・届かないようにする
    notification.save if notification.visitor_id != notification.visited_id && notification.valid?
  end

  # ◆通知機能（領収済）
  def create_notification_paid_fee(current_user, visited_id)
    notification = current_user.active_notifications.new(
      event_id: id,
      visited_id: visited_id,
      action: 'paid_fee'
    )
    notification.save if notification.valid?
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_event_by_event_id, only: [:notice_to_unpaying_users, :progress_status_update, :add_event_user, :add_event_user_fee, :add_event_user_create, :change_restaurant, :change_restaurant_update, :send_remind]
  before_action :ensure_admin?, only: [:show, :edit, :update, :destroy]
  before_action :ensure_admin_event_id?, only: [:progress_status_update, :add_event_user, :add_event_user_fee, :add_event_user_create, :notice_to_unpaying_users, :change_restaurant]
  before_action :set_day_of_the_week, only: [:show, :edit, :change_restaurant, :add_event_user_fee, :add_event_user]

  # 以下、includesはN+1問題の解消
  # 以下、with_deletedは欠席者も含むための記述（gem paranoia）

  def index
    # redirectされるタブをparamsで条件分岐
    case params[:room].to_i
    when 2
      @room = 2
    when 3
      @room = 3
    else
      @room = 1
    end
    # ================タブ１===============
    # 今日のノミカイ
    # 【★幹事＝user_id使用】
    from = Time.current.beginning_of_day
    to = Time.current.end_of_day
    @today_event = Event.find_by(date: from..to, user_id: current_user.id)
    # 曜日
    day_of_the_week(@today_event) if @today_event.present?
    # ToDoリスト
    @todo = Todo.new
    @todos = Todo.where(user_id: current_user.id)
    # ================タブ２===============
    # 全てのノミカイ
    # 【★幹事＝user_id使用】
    @status0_events = Event.where(progress_status: 0, user_id: current_user.id)
    @status1_events = Event.where(progress_status: 1, user_id: current_user.id)
    @status2_events = Event.where(progress_status: 2, user_id: current_user.id)
    # 全てのノミカイ（カレンダー）
    @events = Event.where(user_id: current_user.id)

    # ================タブ３===============
    # 集金中のノミカイ
    @events = Event.where(user_id: current_user.id)
    # 集金中のノミカイ参加メンバー
    # 【★幹事＝user_id使用】
    # 「current_userが幹事のノミカイで、未支払いの飲み会があるUser」の配列
    @users = User.joins(:event_users).where(event_users: { fee_status: false }).joins(:events).where(events: { user_id: current_user.id }).distinct
   end

  def show
    # redirectされるタブをparamsで条件分岐
    case params[:room].to_i
    when 2
      @room = 2
    when 3
      @room = 3
    when 4
      @room = 4
    else
      @room = 1
    end
    # ================タブ２===============
    # 当該飲み会の参加メンバー全員（欠席者含む）
    @event_users = EventUser.with_deleted.includes([:user]).where(event_id: @event.id)
    # ================タブ３===============
    # 当該飲み会に関して未払いのメンバー（欠席者含む）
    @unpaying_event_users = EventUser.with_deleted.includes([:user]).where(event_id: @event.id, fee_status: false)
  end

  # show(タブ１）：ノミカイ基本情報の編集ページ
  def edit
  end

  # show(タブ１）：ノミカイ基本情報の更新
  def update
    if @event.update(event_params)
      flash[:success] = "ノミカイ概要を更新しました"
      redirect_to admin_event_path(@event)
    else
      flash[:danger] = "ノミカイ名を時間は入力必須です"
      redirect_to edit_admin_event_path(@event)
    end
  end

  # show(タブ１）：ノミカイ基本情報の削除
  def destroy
    @event.destroy
    # dependent: :destroyをモデルに記載したため、紐づくnotificationsは@event.destroyで削除されるがevent_userは論理削除が働いてしまうため、物理削除が必要。
    event_users = EventUser.with_deleted.where(event_id: @event.id)
    event_users.each do |event_user|
      event_user.really_destroy!
    end
    redirect_to admin_events_path
  end

  # show(タブ１）：ノミカイ進捗ステータスの更新
  def progress_status_update
    @event.update(event_params)
    # 非同期のため下記削除
    # redirect_back(fallback_location: root_path)
  end

  # show(タブ１）：リマインドメール・通知
  def send_remind
    # 出席者全員に通知を送る
    @event_users = EventUser.where(event_id: @event.id)
    @event_users.each do |event_user|
      @event.create_notification_remind_event(current_user, event_user.user_id)
    end
    RemindMailer.remind_mail(@event).deliver_now
    # 非同期のため下記削除
    # redirect_back(fallback_location: root_path)
  end

  # show(タブ２）：参加メンバーの追加編集ページ
  def add_event_user
    members = current_user.matchers
    @unselected_members = members - User.joins(:event_users).where(event_users: { event_id: @event.id })
  end

  # show(タブ２）：参加メンバーの追加後会費設定編集ページ
  def add_event_user_fee
    @event_user_ids = session[:event_user_ids] = params[:event_user][:ids].drop(1)
    redirect_to(admin_event_path(@event, room: 2)) && return if params[:back]
    # メンバーを選択せずNextボタンを押した場合進めない
    if @event_user_ids.blank?
      flash[:danger] = "メンバーを選択してください"
      redirect_to admin_add_event_user_path(@event)
    end
  end

  # show(タブ２）：参加メンバーの追加更新
  def add_event_user_create
    @event_user_ids = session[:event_user_ids]
    # 下記、Backボタン押した場合renderするための記述
    members = current_user.matchers
    @unselected_members = members - User.joins(:event_users).where(event_users: { event_id: @event.id })
    render(:add_event_user) && return if params[:back]
    # 確定ボタン押した場合
    event_user_ids = session[:event_user_ids]
    event_user_fees = session[:fees] = params[:fees]
    add_event_users = event_user_ids.zip(event_user_fees).map do |event_user_id, event_user_fee|
      # 下記記述がないと会費を入力しなかった場合EventUserが保存されない
      event_user_fee = 0 if event_user_fee.empty?
      EventUser.create(user_id: event_user_id, event_id: @event.id, fee: event_user_fee)
    end

    # ノミカイ招待メール
    if params[:mail]
      InvitationMailer.invitation_mail_for_add_participant(@event, add_event_users).deliver_now
    end
    # 通知機能
    add_event_users.each do |add_event_user|
      @event.create_notification_new_event(current_user, add_event_user.user_id)
    end
    flash[:success] = "参加メンバーを追加しました"
    redirect_to admin_event_path(@event, room: 2)
  end

  # show(タブ３）：未払いの参加メンバー全員に通知を送る
  def notice_to_unpaying_users
    @unpaying_event_users = EventUser.with_deleted.where(event_id: @event.id, fee_status: false)
    @unpaying_event_users.each do |unpaying_event_user|
      @event.create_notification_require_fee(current_user, unpaying_event_user.user_id)
      # メール通知
      UnpaidMailer.unpaid_mail(unpaying_event_user).deliver_now
    end
    # 非同期のため下記削除
    # redirect_back(fallback_location: root_path)
  end

  # show(タブ４）：お店の変更ページ
  # form内にsubmitボタンが複数ある。このアクション自体はGET（PATCHでも記述を変えれば問題はない）
  def change_restaurant
    # ぐるなびAPI
    api_key = Rails.application.credentials.grunavi[:api_key]
    url = 'https://api.gnavi.co.jp/RestSearchAPI/v3/?keyid='
    url << api_key
    if params[:freeword]
      word = params[:freeword]
      url << "&name=" << word
    end
    url = URI.encode(url)
    uri = URI.parse(url)
    json = Net::HTTP.get(uri)
    result = JSON.parse(json)
    @rests = result["rest"]
    restaurant = eval("#{params[:restaurant]}")
    if params[:change]
      # お店を選択していない場合は同じページに戻る
      if params[:restaurant]
        @restaurant = Restaurant.create(
          user_id: current_user.id,
          name: restaurant["name"],
          address: restaurant["address"],
          access: restaurant["access"]["line"] + " " + restaurant["access"]["station"] + restaurant["access"]["station_exit"] + " 徒歩" + restaurant["access"]["walk"] + "分",
          url: restaurant["url"],
          shop_image: restaurant["image_url"]["shop_image1"],
          tel: restaurant["tel"],
          opentime: restaurant["opentime"],
          holiday: restaurant["holiday"]
        )
        @event.update(restaurant_id: @restaurant.id)
        flash[:success] = "お店を変更しました"
        redirect_to admin_event_path(@event, room: 4)
      else
        flash.now[:danger] = "お店を選択してください"
        render :change_restaurant
      end
    end
    redirect_to admin_event_path(@event, room: 4) if params[:back]
  end

  # 新規作成(1)：基本情報入力ページ表示（GET)
  def step1
    @event = Event.new
  end

  # 新規作成(2)：step1更新＋お店検索ページ表示＋正しく選択されていればstep3へリダイレクト（POST：viewあり)
  # form内にsubmitボタンが複数ある。リダイレクトのためstep3はGET、createされる
  def step2
    @event = Event.new(event_params)
    if @event.invalid?
      flash.now[:danger] = "必要情報を入力してください"
      render :step1
    end
    # 【★幹事＝user_id使用】
    @event.user_id = current_user.id
    # ぐるなびAPI
    api_key = Rails.application.credentials.grunavi[:api_key]
    url = 'https://api.gnavi.co.jp/RestSearchAPI/v3/?keyid='
    url << api_key
    if params[:freeword]
      word = params[:freeword]
      url << "&name=" << word
    end
    url = URI.encode(url)
    uri = URI.parse(url)
    json = Net::HTTP.get(uri)
    result = JSON.parse(json)
    @rests = result["rest"]
    restaurant = eval("#{params[:restaurant]}")
    if params[:next]
      # お店を選択していない場合は同じページに戻る
      if params[:restaurant]
        session[:name] = restaurant["name"]
        session[:address] = restaurant["address"]
        session[:access] = restaurant["access"]["line"] + " " + restaurant["access"]["station"] + restaurant["access"]["station_exit"] + " 徒歩" + restaurant["access"]["walk"] + "分"
        session[:url] = restaurant["url"]
        session[:tel] = restaurant["tel"]
        session[:shop_image] = restaurant["image_url"]["shop_image1"]
        session[:opentime] = restaurant["opentime"]
        session[:holiday] = restaurant["holiday"]
        # step3をgetにしたためf.hiddenで渡せないので redirect_toのオプションでparamsを送る
        redirect_to admin_step3_path(event: event_params)
      else
        flash.now[:danger] = "お店を選択してください"
        render :step2
      end
    end
    render(:step1) && return if params[:back]
  end

  # 新規作成(3)：メンバー選択ページの表示（GET)
  def step3
    @members = current_user.matchers
    @event = Event.new(event_params)
    # 【★幹事＝user_id使用】
    @event.user_id = current_user.id
    render :step2 if @event.invalid?
  end

  # 新規作成(4)：step3のparamsの値をsessionに代入＋会費設定ページの表示（POST：viewあり)
  def step4
    @event = Event.new(event_params)
    # # 【★幹事＝user_id使用】
    @event.user_id = current_user.id
    @event_user_ids = session[:event_user_ids] = params[:event_user][:ids].drop(1)
    render(:step2) && return if params[:back]
    if @event_user_ids.blank?
      @members = current_user.matchers
      flash.now[:danger] = "参加者を１人以上選択してください"
      render(:step3)
    end
  end

  # 新規作成(5)：step4のparamsの値をsessionに代入＋step4のparamsの値をsessionに代入＋確認ページの表示（POST：viewあり)
  def confirm

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/views/admin/events/_progress_stepbar.html.erb
<div>
  <div class="progress__flash-message"></div>
  <%= form_with model: event, url: admin_events_progress_status_path(event.id), remote: true, class:"progress-status"  do |f| %>
    <%= f.select :progress_status, [ ["招待済",0], ["お店予約済", 1], ["リマインド済", 2 ] ,["終了済", 3] ], class: "admin" %>
    <%= f.submit "更新",class:"btn blue-btn btn-sm" %>
  <% end %>
</div>
<div class="progress__stepbar">
  <% case event.progress_status %>
  <% when 0 then %>
    <ul class="bootstrapWizard form-wizard">
      <li class="active" data-target="#step1"><span class="step">1</span><span class="title stepbar-tittle admin">メンバを招待済</span> </li>
      <li data-target="#step2" class=""><span class="step">2</span><span class="title stepbar-tittle admin">お店予約済</span> </li>
      <li data-target="#step3" class=""><span class="step">3</span><span class="title stepbar-tittle admin">リマインド済</span> </li>
      <li data-target="#step4" class=""><span class="step">4</span><span class="title stepbar-tittle admin">終了済</span> </li>
    </ul>
    <div class="clearfix"></div>
    <div class="remind-mail"> 
      <%=link_to admin_events_send_remind_path(event.id), class:"btn orange-btn", remote: true do %>
        <i class="fas fa-envelope admin-icon"></i>&nbsp;<i class="fas fa-bell admin-icon"></i>&ensp;全員にリマインドメール・通知を送る 
      <% end %>
      <p class="text-muted">※ リマインドメールはノミカイ前日に自動で送信されます。別途手動で送信したい場合は上記ボタンから送信できます。</p>
    </div>
  <% when 1 then %>
    <ul class="bootstrapWizard form-wizard">
      <li class="" data-target="#step1"><span class="step">1</span><span class="title stepbar-tittle admin">メンバを招待済</span> </li>
      <li data-target="#step2" class="active"><span class="step">2</span><span class="title stepbar-tittle admin">お店予約済</span> </li>
      <li data-target="#step3" class=""><span class="step">3</span><span class="title stepbar-tittle admin">リマインド済</span> </li>
      <li data-target="#step4" class=""><span class="step">4</span><span class="title stepbar-tittle admin">終了済</span> </li>
    </ul>
    <div class="clearfix"></div>
    <div class="remind-mail"> 
      <%=link_to admin_events_send_remind_path(event.id), class:"btn orange-btn", remote: true do %>
        <i class="fas fa-envelope admin-icon"></i>&nbsp;<i class="fas fa-bell admin-icon"></i>&ensp;全員にリマインドメール・通知を送る 
      <% end %>
      <p class="text-muted">※ リマインドメールはノミカイ前日に自動で送信されます。別途手動で送信したい場合は上記ボタンから送信できます。</p>
    </div>
  <% when 2 then %>
    <ul class="bootstrapWizard form-wizard">
      <li class="" data-target="#step1"><span class="step">1</span><span class="title stepbar-tittle admin">メンバを招待済</span> </li>
      <li data-target="#step2" class=""><span class="step">2</span><span class="title stepbar-tittle admin">お店予約済</span> </li>
      <li data-target="#step3" class="active"><span class="step">3</span><span class="title stepbar-tittle admin">リマインド済</span> </li>
      <li data-target="#step4" class=""><span class="step">4</span><span class="title stepbar-tittle admin">終了済</span> </li>
    </ul>
    <div class="clearfix"></div>
  <% when 3 then %>
    <ul class="bootstrapWizard form-wizard">
      <li class="" data-target="#step1"><span class="step">1</span><span class="title stepbar-tittle admin">メンバを招待済</span> </li>
      <li data-target="#step2" class=""><span class="step">2</span><span class="title stepbar-tittle admin">お店予約済</span> </li>
      <li data-target="#step3" class=""><span class="step">3</span><span class="title stepbar-tittle admin">リマインド済</span> </li>
      <li data-target="#step4" class="active"><span class="step">4</span><span class="title stepbar-tittle admin">終了済</span> </li>
    </ul>
    <div class="clearfix"></div>
  <% end %>
</div>

app/views/admin/events/_tab3.html.erb
<!-- 未払いメンバー一覧 -->
<div class="content__block__unpaid-participants content__block admin-table">
  <h2 class="block-hedding">集金中のメンバー</h2>
  <% if unpaying_event_users.with_deleted.present? %>
    <h2 class="block-hedding"><%= unpaying_event_users.with_deleted.count %>名</h2>
    <table class="table members-table">
      <thead>
        <tr>
          <th scope="col" class="participants-image-head"></th>
          <th scope="col"></th>
          <th scope="col">氏名</th>
          <th scope="col">会費</th> 
          <%# モーダルを表示するボタン %>
           <th scope="col">支払い状況<br><span class="sm-modal-btn" id="paid-modal-btn-1"><i class="far fa-question-circle"></i></span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% unpaying_event_users.each do |unpaying_event_user| %>
          <%# 参照先のS3オブジェクトURLを作成 %>
          <% image_url = "https://dmm-cloud-lesson10-image-files-resize.s3-ap-northeast-1.amazonaws.com/store/" + unpaying_event_user.user.image_id + "-thumbnail." %>
          <tr>
            <div class="">
              <% if unpaying_event_user.deleted_at.nil? %>
                <td></td>
              <% else%>
                <td><span class="badge badge-danger">欠席</span></td>
              <% end %>
            </div>
            <%# S3+Lambdaで表示 %>
            <td scope="row" class="participants-image"><%= link_to admin_user_path(unpaying_event_user.user.id),class:"" do %><%= image_tag(image_url, fallback: "no_image.jpg", class:"small-image") %><% end %></td>
            <td class="participants-name"><%= link_to admin_user_path(unpaying_event_user.user.id),class:"nomal-font responsive-font-sm" do %><%= unpaying_event_user.user.name %><% end %></td>
            <td class="nomal-font responsive-font-sm"><%= unpaying_event_user.fee %>円</td>
            <td class="event-users-fee-status_<%= unpaying_event_user.id %>">
            <%# 会員ごとの会費ステータス変更フォーム(非同期) %>
            <%= render 'admin/event_users/event_users_fee_status', event_user: unpaying_event_user %>
          </td>
            <td>
              <%# current_user(自分)の場合はDMボタンを表示しない %>
              <% unless unpaying_event_user.user == current_user %>
                <%=link_to admin_room_path(unpaying_event_user.user), class:"btn btn-sm blue-btn" do %><i class="fas fa-comments admin-icon"></i><% end %>
              <% end %>     
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="notice-to-unpaying-users-button">
      <%=link_to admin_notice_to_unpaying_users_path(@event), class:"btn orange-btn",remote: true do %>
        <i class="fas fa-envelope admin-icon"></i>&nbsp;<i class="fas fa-bell admin-icon"></i>&ensp;支払い依頼通知・メールを送る
      <% end %>
      <%# モーダルを表示するボタン %>
      <span class="modal-btn" id="unpaid-modal-btn"><i class="far fa-question-circle"></i></span>
    </div>
  <% else %>
  全員領収済
  <% end %>
</div>
<!-- メンバーごとの会費、支払いステータス変更 -->
<div class="content__block__participants-fee-status admin-table">
  <h2 class="block-hedding">メンバーごとの会費・集金状況</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col" class="participants-image-head"></th>
        <th scope="col">氏名<br><br></th>
        <th scope="col">会費<br><span class="text-muted">※半角英数字</span></th>
        <%# モーダルを表示するボタン %>
        <th scope="col">支払い状況<br><span class="sm-modal-btn" id="paid-modal-btn-2"><i class="far fa-question-circle"></i></span></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% event_users.each do |event_user| %>
        <%# 参照先のS3オブジェクトURLを作成 %>
        <% image_url = "https://dmm-cloud-lesson10-image-files-resize.s3-ap-northeast-1.amazonaws.com/store/" + event_user.user.image_id + "-thumbnail." %>
        <tr>
          <% if event_user.deleted_at.nil? %>
            <td></td>
          <% else%>
            <td><span class="badge badge-danger">欠席</span></td>
          <% end %>
          <%# S3+Lambdaで表示 %>
          <td scope="row" class="participants-image"><%= link_to admin_user_path(event_user.user),class:"" do %><%= image_tag(image_url, fallback: "no_image.jpg", class:"small-image") %><% end %></td>
          <td class="participants-name"><%= link_to admin_user_path(event_user.user),class:"nomal-font responsive-font-sm" do %><%= event_user.user.name %><% end %></td>
          <td class="event-users-fee_<%= event_user.id %>">
            <%# 会員ごとの会費変更フォーム(非同期) %>
            <%= render 'admin/event_users/event_users_fee', event_user: event_user %>
          </td>
          <td class="event-users-fee-status_<%= event_user.id %>" >
            <%# 会員ごとの会費ステータス変更フォーム(非同期) %>
            <%= render 'admin/event_users/event_users_fee_status', event_user: event_user %>
          </td>
          <td>
            <%# current_user(自分)の場合はDMボタンを表示しない %>
            <% unless event_user.user == current_user %>
              <%=link_to admin_room_path(event_user.user.id), class:"btn btn-sm blue-btn" do %><i class="fas fa-comments admin-icon"></i><% end %>
            <% end %>      
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%# モーダル表示画面 %>
<%= render 'modals/admin_event_index_tab3' %>

app/views/admin/events/_tab4.html.erb
<!-- お店情報 -->
<div class="content__block--restaurant content__block admin-table">
  <h2 class="block-hedding">お店情報</h2>
  <span class="restaurant mt-2">
    <%# この箇所の画像は767px未満のみ表示 %>
    <span class= "restaurant-image-responsive">
      <%= image_tag(event.restaurant.shop_image, class: "middle-image") %>
    </span>
  </span>
  <div class="row">
    <table class="table table-borderless col-md-8">
      <tbody>
        <tr>
          <th scope="row">お店名</th>
          <td class="nomal-font"><%= event.restaurant.name %>&emsp;<%= link_to event.restaurant.url, target: :_blank, class: "btn blue-btn btn-sm" do %>ぐるなびで見る<% end %></td>
        </tr>
        <tr>
          <th scope="row">アクセス</th>
          <td class="nomal-font responsive-font-sm"><%= event.restaurant.access %></td>
        </tr>
        <tr>
          <th scope="row">住所</th>
          <td class="nomal-font responsive-font-sm"><%= event.restaurant.address %></td>
        </tr>
        <tr>
          <th scope="row">TEL</th>
          <td class="nomal-font responsive-font-sm"><%= event.restaurant.tel %></td>
        </tr>
        <tr>
          <th scope="row">営業時間</th>
          <td class="nomal-font responsive-font-sm"><%= event.restaurant.opentime %></td>
        </tr>
        <tr>
          <th scope="row">定休日</th>
          <td class="nomal-font responsive-font-sm"><%= event.restaurant.holiday %></td>
        </tr>
      </tbody>
    </table>
    <%# この箇所の画像は767px以上のみ表示 %>
     <div class="col-md-4 restaurant-image">
      <%= image_tag(event.restaurant.shop_image, class: "middle-image") %>
    </div>
  </div>
  <div class="row">
    <div class="d-flex justify-content-end col-12">
          <%= link_to "お店を変更", admin_change_restaurant_path(event), class:"btn blue-btn" %>
        </div>
    </div>
</div>
 <!-- マップ -->
<div class="content__block--map">
  <h2 class="block-hedding admin">お店のMap</h2>
  <div class="google-map">
    <div id='map' class="<%= event.restaurant.address %>"> </div>
  </div>
</div>

<%# マップ(JS)  %>
<script sec="javascripts/address_map.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

app/views/admin/events/send_remind.js.erb
$(".remind-mail").html("<p class='alert alert-success'>送信しました</p>");