config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    passwords: 'public/users/passwords',
    registrations: 'public/users/registrations',
  }
  scope module: :public do
    root 'homes#top'
    resources :events, only: [:show, :index]
    resources :users, only: [:show, :edit, :index, :update] do
      resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
    end
    resources :rooms, only: [:show, :index]
    resources :direct_messages, only: [:create]
    resources :notifications, only: [:index, :destroy]
  end

  namespace :admin do
    resources :users, only: [:show] do
      resources :todos, only: [:create, :destroy]
    end
    resources :events, only: [:show, :index, :edit, :create, :update, :destroy]
    get 'step1', to: 'events#step1'
    post 'step2', to: 'events#step2'
    get 'step3', to: 'events#step3'
    post 'step4', to: 'events#step4'
    post 'confirm', to: 'events#confirm'

    get 'events/:event_id/send_remind', to: 'events#send_remind', as: 'events_send_remind'
    patch 'events/:event_id/progress_status_update', to: 'events#progress_status_update', as: 'events_progress_status'
    get 'events/:event_id/notice_to_unpaying_users', to: 'events#notice_to_unpaying_users', as: 'notice_to_unpaying_users'
    get 'events/:event_id/add_event_user', to: 'events#add_event_user', as: 'add_event_user'
    post 'events/:event_id/add_event_user_fee', to: 'events#add_event_user_fee', as: 'add_event_user_fee'
    post 'events/:event_id/add_event_user', to: 'events#add_event_user_create', as: 'add_event_user_create'
    get 'events/:event_id/change_restaurant', to: 'events#change_restaurant', as: 'change_restaurant'
    patch 'event_users/:event_user_id/fee_status', to: 'event_users#fee_status_update', as: 'event_users_fee_status'
    patch 'event_users/:event_user_id/fee', to: 'event_users#fee_update', as: 'event_users_fee'
    patch 'event_users/:event_user_id/participate_status', to: 'event_users#participate_status_update', as: 'event_users_participate_status'

    resources :rooms, only: [:show, :index]
    resources :direct_messages, only: [:create]
    resources :notifications, only: [:index, :destroy]
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :task
    validates :user_id
  end
end

app/controllers/admin/todos_controller.rb
class Admin::TodosController < ApplicationController
  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    @todo.save if @todo.valid?
    # 非同期実装のため下記削除
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy if @todo.valid?
    # 非同期実装のため下記削除
    # redirect_back(fallback_location: root_path)
  end

  private

  def todo_params
    params.require(:todo).permit(:task)
  end
end

app/helpers/admin/todos_helper.rb
module Admin::TodosHelper
end

app/views/admin/todos/_todos.html.erb
<div class="content__block--todo content__block">
  <h2 class="block-hedding admin">ToDo リスト</h2>
  <%= form_with model: todo, url: admin_user_todos_path(current_user), remote: true, class:"todo-form"  do |f| %>
    <%= f.text_field :task, class:"input-form nomal-font" %>
    <%= f.button type: "submit", class:"btn blue-btn" do %><i class="fas fa-pen admin-icon"></i><% end %>
  <% end %>
  <table class="table table-borderless">
    <tbody class="result_create">
      <% todos.each do |todo| %>
        <tr class="result_delete">
          <td>
            <%= link_to admin_user_todo_path(current_user, todo), method: :delete, remote: true,  class: 'todo-btn blue-btn' do %><i class="fas fa-check-square admin"></i><% end %>
          </td>
          <td class = "admin nomal-font font-sm-responsive">
             <%= todo.task %>
          </td>
        </tr>
      <% end %>
      <%# <tr class="result_create result_delete"></tr> %>
    </tbody>
  </table>
</div>

app/views/admin/todos/create.js.erb
  $(".result_create").append('<tr class="result_delete"><td><%= link_to admin_user_todo_path(current_user, @todo), method: :delete, remote: true,  class: 'todo-btn blue-btn' do %><i class="fas fa-check-square admin"></i><% end %></td><td class = "admin nomal-font font-sm-responsive"><%= @todo.task %></td></tr>')
  <%# valメソッドはコメント送信後のコメント入力フォームを空に %>
  $('input[type=text]').val("");




  

app/views/admin/todos/destroy.js.erb
$(".result_delete").remove(':contains(<%= @todo.task %>)')