config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    passwords: 'public/users/passwords',
    registrations: 'public/users/registrations',
  }
  scope module: :public do
    root 'homes#top'
    resources :events, only: [:show, :index]
    resources :users, only: [:show, :edit, :index, :update] do
      resource :relationships, only: [:create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
    end
    resources :rooms, only: [:show, :index]
    resources :direct_messages, only: [:create]
    resources :notifications, only: [:index, :destroy]
  end

  namespace :admin do
    resources :users, only: [:show] do
      resources :todos, only: [:create, :destroy]
    end
    resources :events, only: [:show, :index, :edit, :create, :update, :destroy]
    get 'step1', to: 'events#step1'
    post 'step2', to: 'events#step2'
    get 'step3', to: 'events#step3'
    post 'step4', to: 'events#step4'
    post 'confirm', to: 'events#confirm'

    get 'events/:event_id/send_remind', to: 'events#send_remind', as: 'events_send_remind'
    patch 'events/:event_id/progress_status_update', to: 'events#progress_status_update', as: 'events_progress_status'
    get 'events/:event_id/notice_to_unpaying_users', to: 'events#notice_to_unpaying_users', as: 'notice_to_unpaying_users'
    get 'events/:event_id/add_event_user', to: 'events#add_event_user', as: 'add_event_user'
    post 'events/:event_id/add_event_user_fee', to: 'events#add_event_user_fee', as: 'add_event_user_fee'
    post 'events/:event_id/add_event_user', to: 'events#add_event_user_create', as: 'add_event_user_create'
    get 'events/:event_id/change_restaurant', to: 'events#change_restaurant', as: 'change_restaurant'
    patch 'event_users/:event_user_id/fee_status', to: 'event_users#fee_status_update', as: 'event_users_fee_status'
    patch 'event_users/:event_user_id/fee', to: 'event_users#fee_update', as: 'event_users_fee'
    patch 'event_users/:event_user_id/participate_status', to: 'event_users#participate_status_update', as: 'event_users_participate_status'

    resources :rooms, only: [:show, :index]
    resources :direct_messages, only: [:create]
    resources :notifications, only: [:index, :destroy]
  end
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  # paranoia
  acts_as_paranoid

  # ==============アソシエーション ================================
  belongs_to :user
  belongs_to :event

  # ==============バリデーション ================================
  # feeは半角英数字（integerなので下記記載なくても０になる)
  validates :fee, format: { with: /\A[a-zA-Z0-9]+\z/ }
end

app/controllers/admin/event_users_controller.rb
class Admin::EventUsersController < ApplicationController
  before_action :set_event_user, only: [:fee_update, :fee_status_update]
  before_action :ensure_admin?, only: [:participate_status_update]
  before_action :ensure_admin_event_id?, only: [:fee_update, :fee_status_update]

  # 欠席の場合、論理削除
  def participate_status_update
    @event_user = EventUser.with_deleted.find_by(event_id: params[:event_id], user_id: params[:user_id])
    @event_user.update(deleted_at: params[:deleted_at])
    # 非同期のため下記削除
    # redirect_back(fallback_location: root_path)
  end

  # 参加メンバーことの会費変更（欠席者含む）
  def fee_update
    # 下記のようにnilの場合を書かないと、入力がnilでもデータベースは更新されない
    if @event_user.fee_status == false
      if params[:event_user][:fee].present?
        @event_user.update(event_user_params)
      else
        @event_user.update(fee: 0)
      end
    end
    # 非同期のため下記削除
    # redirect_back(fallback_location: root_path)
  end

  # 参加メンバーことの会費ステータス変更（欠席者含む）
  def fee_status_update
    @event_user.update(event_user_params)
    # メール
    PaidMailer.paid_mail(@event_user).deliver_now
    # 通知機能
    @event_user.event.create_notification_paid_fee(current_user, @event_user.user_id)
    # 非同期のため下記削除
    # redirect_back(fallback_location: root_path)
  end

  private

  def set_event_user
    @event_user = EventUser.with_deleted.find_by(event_id: params[:event_user][:event_id], user_id: params[:event_user][:user_id])
  end

  def event_user_params
    params.require(:event_user).permit(:fee, :fee_status, :deleted_at)
  end

  # 自分がカンジでないノミカイはアクセス(URL検索含む）できないようにする
  def ensure_admin?
    @event = Event.find(params[:event_id])
    redirect_back(fallback_location: root_path) unless @event.user_id == current_user.id
  end

  def ensure_admin_event_id?
    @event = Event.find(params[:event_user][:event_id])
    redirect_back(fallback_location: root_path) unless @event.user_id == current_user.id
  end
end

app/helpers/admin/event_users_helper.rb
module Admin::EventUsersHelper
end

app/views/admin/event_users/_event_users_fee.html.erb
<%# 会員ごとの会費変更フォーム(非同期) %>
<% if event_user.fee_status == false %>
  <%= form_with model: event_user,url: admin_event_users_fee_path(event_user.id), romote: true, class:"event-fee-form font-xs-responsive" do |f| %>
    <%= f.text_field :fee, class:"event-fee-form__form nomal-font", size: 7 %><span class="nomal-font" >円</span>
    <%= f.hidden_field :user_id, value: event_user.user_id %>
    <%= f.hidden_field :event_id, value: event_user.event_id %>
    <%= f.submit "更新",class:"btn btn-sm btn-xs admin-white-btn" %>
  <% end %>
<% else %>
  <span class="nomal-font admin font-xs-responsive"><%= event_user.fee%>円</span>
<% end %>

app/views/admin/event_users/_event_users_fee_status.html.erb
<%# 会員ごとの会費ステータス変更フォーム(非同期) %>
  <% if event_user.fee_status == false %>
    <%= form_with model: event_user, url: admin_event_users_fee_status_path(event_user.id), class:"participant-fee-status-form"  do |f| %>
    <%= f.hidden_field :fee_status, value: true %>
    <%= f.hidden_field :user_id, value: event_user.user_id %>
    <%= f.hidden_field :event_id, value: event_user.event_id %>
    <%= f.submit "未領収",class:"btn btn-sm orange-btn participant-fee-status-form__btn" %>
    <% end %>
  <% else %>
    <p class="btn btn-sm faked-gray-btn participant-fee-status-form__btn" >領収済</p>
  <% end %>

app/views/admin/event_users/_participate_button.html.erb
<% if event_user.deleted_at == nil %>
  <p><%=link_to "参加", admin_event_users_participate_status_path(event_user.id, user_id: event_user.user_id, event_id: event_user.event_id, deleted_at: Time.now ), method: :patch, remote: true, class:"btn btn-secondary btn-sm" %></p>
<% else %>
  <p><%=link_to "欠席", admin_event_users_participate_status_path(event_user.id, user_id: event_user.user_id, event_id: event_user.event_id, deleted_at: "" ), method: :patch, remote: true, class:"btn btn-danger btn-sm" %></p>
<% end %>

app/views/admin/event_users/fee_status_update.js.erb
<%# 会員ごとの会費ステータス変更フォーム(非同期) %>
$(".event-users-fee-status_<%= @event_user.id %>").html("<%= j(render 'admin/event_users/event_users_fee_status', event_user: @event_user) %>");
$(".event-users-fee-status_<%= @event_user.id %>").append("<p class='alert-success font-sm-responsive'>メールを送信しました</p>");
$(".event-users-fee_<%= @event_user.id %>").html("<span class='nomal-font admin font-xs-responsive'><%= @event_user.fee%>円</span>");

app/views/admin/event_users/fee_update.js.erb
<%# 会員ごとの会費変更フォーム(非同期) %>
$(".event-users-fee_<%= @event_user.id %>").html("<%= j(render 'admin/event_users/event_users_fee', event_user: @event_user) %>");
$(".event-users-fee_<%= @event_user.id %>").append("<p class='alert-success font-sm-responsive'>更新しました</p>");

app/views/admin/event_users/participate_status_update.js.erb
$(".participate_<%= @event_user.id %>").html("<%= j(render 'admin/event_users/participate_button', event_user: @event_user) %>");